### PR TITLE
Fix msie detection, jQuery deprecates $.browser from 1.3+ removed from 1.9+

### PR DESCRIPTION
**Pull request by jasonm23**
Ideally, plugins should use modernizer now for browser shimming.

### CODE REVIEW

**Comment by jasonm23** [comment]
For the moment I have to add 

```
jQuery.browser = {}
```

To monkey patch this into a forced fail.

**Comment by svscorp** [comment]
Yeah, that's an annoying issue :( Will it be merged and new jenkins bugfix released? @jenkinsadmin @geoffbullen @kohsuke @KostyaSha

**Comment by KostyaSha** [comment]
Hi, @jenkinsadmin is a bot. I spent some time bugfixing and releasing new version, but i'm not an author/permanent maintainer. If you confirm that your changes has no regressions and fixed issue, then i can merge and run release. But you will be responsible for issue that your change will cause. Is it ok for you?

**Comment by svscorp** [comment]
@KostyaSha Thanks for fast reply! I am checking. This PR is not solving all the issues. There is another file same issue exists.

I fixed it locally and got a fancybox window on 'Run' click, with parameters and Project Start options.

Can I be responsible for that plugin? Well, I can take responsibility for that change, but a bit later, once I test it more. Whom can I ping to merge/build new bugfix release?

**Comment by KostyaSha** [comment]
I can merge/release when you will be sure. Also if it possible you can implement a selenium web test.

**Comment by CloCkWeRX** [comment]
Which is better, this or #78

**Comment by dalvizu** [comment]
Choosing #78 over this

**Pull request closed without merging**
