### PR TITLE
[JENKINS-31085] Add anchor for each pipeline number.

### PR DESCRIPTION
**Pull request by dalvizu**
[JENKINS-31085](https://issues.jenkins-ci.org/browse/JENKINS-31085)

This allows me to link to exact pipeline in a URL, assuming that it
is a displayed build. For example:

http://jenkins:8080/view/my-pipline/#101

### CODE REVIEW

**Comment by dalvizu** [comment]
@recena can you review please? Are you the current owner of the plugin?

**Comment by recena** [comment]
@dalvizu I'm only try to help here. I'll back here after this [JENKINS-30846](https://issues.jenkins-ci.org/browse/JENKINS-30846)

**Comment by recena** [comment]
@dalvizu Where is the JIRA ticket associated to this PR?

**Comment by dalvizu** [comment]
There isn't one

**Comment by recena** [comment]
@dalvizu For this kind of PR we need a JIRA ticket explaining what do you want to.

**Comment by dalvizu** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-31085

**Comment by recena** [comment]
@dalvizu Thanks.

**Comment by dalvizu** [comment]
Closing - I mucked up my remote

**Pull request closed without merging**
