### PR TITLE
CSS Layout: Keep table row on a single line

### PR DESCRIPTION
**Pull request by alex-yh99**
Hide the overflow on td 'param-value'

----

orig

----

Fixed: 

fixed

### CODE REVIEW

**Comment by KostyaSha** [comment]
What jenkins core version do you use? Could you verify that your change correctly works on core version defined in pom? Why right space is overflowed on your screenshot?

**Comment by alex-yh99** [comment]
@KostyaSha Sorry for the late reply
I was using Jenkins ver. 1.617, and by the time the PR is submitted, the build-pipeline-plugin version was 1.4.7.
I've just upgraded the plugin to 1.4.8, and the layout seems to be fixed. (Also the right space won't overflow either).

However since my builds have really long params passed, there are still some tiny layout issues.

Thanks for your great work. Regards

default

**Comment by dalvizu** [comment]
@alex-yh99 - can you re-test on latest master? I believe @fishermans fixed your issue here new layout issue has been fixed here:

https://github.com/jenkinsci/build-pipeline-plugin/pull/92

**Comment by alex-yh99** [comment]
Thanks @dalvizu 
I've replaced the css files from the master branch, and everything works.
I would close the pr, Also thanks @fishermans for the fix.

aaxx

**Pull request closed without merging**
