### PR TITLE
[Fixed JENKINS-29477]

### PR DESCRIPTION
**Pull request by fishermans**
Please find a fix for issue [JENKINS-29477](http://issues.jenkins-ci.org/browse/JENKINS-29477).

### CODE REVIEW

**Comment by recena** [comment]
@fishermans I was working on JENKINS-29477. Anyway, if you PR solve the issue, will be great. Could you provide a screenshot with the result?

**Comment by fishermans** [comment]
image

**Comment by recena** [comment]
@fishermans Nice! I have a very similar proposal. :+1:

**Comment by recena** [comment]
@fishermans Let me do some tests, ok?

**Comment by fishermans** [comment]
Sure. As you can see in my screen shot it was important to me to find a workaround. :-)

**Comment by dalvizu** [comment]
+1

**Comment by recena** [comment]
:+1:

**Pull request merged**
