### PR TITLE
fix image size to support retina display

### PR DESCRIPTION
**Pull request by macdao**

### CODE REVIEW

**Comment by dalvizu** [comment]
Can you provide an example (screenshot) of how the image is broken on a retina display?

**Comment by macdao** [comment]
@dalvizu when I changed the images to retina size(48x48 for an 24x24-original png) the image is double size on the retina screen. So I have to fix the images size to 24x24 to make it right.

**Comment by dalvizu** [comment]
Hey sorry for the late reply. Can you describe what 'changed the images to retina size' means? I do not understand this and can't reproduce this myself, and without a screenshot I cannot visualize what the problem this.

I see the images as 16x16. Why are they being set to 24x24?

**Comment by dalvizu** [comment]
No activity, closing

**Pull request closed without merging**
