### PR TITLE
[JENKINS-68022] Fix icon usage

### PR DESCRIPTION
**Pull request by alecharp**
Since Jenkins `2.337` and https://github.com/jenkinsci/jenkins/pull/5778, the PNG icons were removed from Jenkins core. Only SVG files remains. 

With this PR, I propose a fix to use the image correctly on recent versions of Jenkins. See the before in [JENKINS-68022](https://issues.jenkins.io/browse/JENKINS-68022) 

Sadly, the first commit was mandatory here to be able to start the plugin locally, and so anyone can test the changes.

<details>
<summary>After:</summary>

Screen Shot 2022-05-17 at 18 08 16
</details>

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by soprano8086** [comment]
Hi, 
We hit this issue recently. Anyone can fix the test and merge? 
Thanks

**Comment by taylorbasso** [comment]
Also running into this... Unfortunately I was not able to build this locally due to some access-modifier-checker error

`[INFO] --- access-modifier-checker:1.27:enforce (default-enforce) @ build-pipeline-plugin ---
[ERROR] au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTrigger$DescriptorImpl:310 hudson/tasks/Messages must not be used
[ERROR] au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTrigger$DescriptorImpl:314 hudson/tasks/Messages must not be used
[ERROR] au/com/centrumsystems/hudson/plugin/buildpipeline/trigger/BuildPipelineTrigger$DescriptorImpl:318 hudson/tasks/Messages must not be used
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.179 s
[INFO] Finished at: 2022-08-02T15:29:54-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kohsuke:access-modifier-checker:1.27:enforce (default-enforce) on project build-pipeline-plugin: Access modifier checks failed. See the details above -> [Help 1]
`

**Comment by alexhass** [comment]
As interrim workaround I copied all the images into the required folder, but this is not a good solution.

When can we expect a fix?

**Comment by Panajev** [comment]
Sorry for pinging about this, bit is there any update on this?

**Comment by Vincevrp** [comment]
> As interrim workaround I copied all the images into the required folder, but this is not a good solution.
> 
> When can we expect a fix?

I've temporarily done the same thing. Is there any update on this?

**Comment by aikar** [comment]
For anyone else wanting to restore it as previous people mentioned they did, if you go download some say 2xx build of jenkins .war file, extract the files with unzip blah.war

then delete any svg's in the images folder
`find images -name "*.svg" -delete`

then update your current war with
`jar uvf /path/to/2.361.2.war images/`

the svg part is important to not overwrite any existing svg's or itll break the verification from web-inf folder. 
Wasn't important enough to polish anymore than this for now.

**Comment by ryanwaite28** [comment]
Hi, is there any intention on merging this PR?

**Comment by alecharp** [comment]
@dalvizu would you be able to review this PR and potentially merge it and release the plugin? It seems that this fix would help users.

**Review by PK89SC — APPROVED** [review]

**Review by gluehbirnenkopf — APPROVED** [review]

**Comment by alexhass** [comment]
Any chance for a release?

**Comment by kumadee** [comment]
@gluehbirnenkopf @PK89SC @ravindrareddy-cht Any idea when this fix will be merged and released? It's annoying.

**Comment by zia-aws** [comment]
Any idea when this going to be released?

**Comment by arpit-patel1** [comment]
Hi, Is there any plans on this PR being merged ? I would really like to help out here if needed. Please let me know.

**Comment by MarkEWaite** [comment]
@alexhass , @kumadee, @zia-aws, and @arpit-patel1 the fix is unlikely to be released unless one or more of you [adopt the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/), merge the fix, and release a new version of the plugin.

There are now two other pull requests that build on the work in this pull request.  Those pull requests make it easier for someone to adopt the plugin.

* #125 
* #126

**Comment by dalvizu** [comment]
Cherry picked and merged in https://github.com/jenkinsci/build-pipeline-plugin/pull/126

**Comment by dalvizu** [comment]
Released in 2.0.0

**Comment by MarkEWaite** [comment]
Thanks very much @dalvizu !

**Pull request closed without merging**
