### PR TITLE
Support Build Flow Job

### PR DESCRIPTION
**Pull request by tangkun75**
When the job is kind of build flow (via build-flow-plugin - https://github.com/jenkinsci/build-flow-plugin), we'll traverse its downstream builds with its job graphs and show them on the build grid. Of course, the project grid can't show their relationships well because project is used for showing static relationship among jobs, but build grid for dynamic (that is - it'll show whatever happened in that execution chain).

### CODE REVIEW

**Comment by cdenneen** [comment]
@tangkun75 can you update this PR to resolve conflicts?
@recena @dalvizu Can this feature be implemented?
As currently implemented this plugin doesn't allow itself to do notifications or be triggered so that's where BuildFlow would work nicely but since this model won't follow build-flow parent/child flow the UI doesn't look correct.

**Comment by cdenneen** [comment]
screen shot 2016-02-09 at 1 58 28 pm

I'm curious Layout only has one option... could this be where BuildFlow is enabled?
What's the purpose of this Layout dropdown? What are other options here?

**Comment by tangkun75** [comment]
I'll work on it:

**Comment by cdenneen** [comment]
@jenkinsadmin can someone merge this?

**Comment by recena** [comment]
@cdenneen This has to be reviewed /cc @dalvizu

**Comment by dalvizu** [comment]
This can't be merged without first resolving the merge conflicts. 

That said there is an issue beyond just the merge conflict: this is not adding the behavior in the way @kohsuke created to extend it based on the open-closed principle: ProjectGridBuilder

This is the 'Layout' drop-down you see. It only has one because the build-pipeline-plugin provides a deafult implementation. I believe another plugin implements this to provide fingerprinting - I can't find it though. @recena do you know?

This PR accomplishes this extension by overriding the 'Upstream/Downstream' way of building the grid. However, this in turn is called by the grid builder:

https://github.com/jenkinsci/build-pipeline-plugin/blob/master/src/main/java/au/com/centrumsystems/hudson/plugin/buildpipeline/DownstreamProjectGridBuilder.java#L117

@cdenneen I'm not sure what you mean by this comment:

> As currently implemented this plugin doesn't allow itself to do notifications or be triggered [...]

What do you mean by 'do notifications' or 'be triggered'?

**Comment by cdenneen** [comment]
@dalvizu what I meant is currently I trigger a build-flow job which captures the build status of downstream jobs. Normal upstream/downstream jobs don't update parent of child fails. So I'd like to trigger the build pipeline itself but it doesn't support things like the gitlab-plugin or GitHub merge request because it's not an actual "job". Would be nice if it could be triggered as such and update git build status of the entire pipeline.

**Comment by dalvizu** [comment]
>  I'd like to trigger the build pipeline itself but it doesn't support things like the gitlab-plugin or GitHub merge request because it's not an actual "job"

Maybe I'm misunderstanding, but yes out of the box you absolutely can trigger a pipeline: its triggers are whatever triggers the initial build, so all of the triggers a jenkins build gets, including gitlab plugin, github merge request, everything in jenkins basically.

Outside of build-flow, the pipeline itself does not fail, but its point is to be able to visualize and retry failed builds in the pipeline, and from that perspective you do not want the whole pipeline to fail. I am curious how this PR handles rebuilding of stages? It sounds like it just does the visualization part.

**Comment by cdenneen** [comment]
Correct you'd trigger the build of job1 which would "trigger" this pipeline
but it won't give the entire pipeline a pass/fail only that first job would
return status to webhook that called it. This is why I've used the
build-flow which bubbles up the status. So was curious about using pipeline
as a replacement for flow if I could capture status of entire pipeline.
Since that's not possible implementing this PR, in the proper way of
course, to visualize flow would allow me to use flow job as the trigger
point and overall status of pipeline while still being able to visualize
that pipeline similar to upstream/downstream that the pipeline currently
supports.

**Comment by tangkun75** [comment]
Hi @recena, @dalvizu  and @cdenneen,
     If possible, let us discuss what (requirements) need for this feature: supporting Build Flow job for this plugin. And I can re-implement them.

**Comment by tangkun75** [comment]
Below is my scenario: in my build process, we use build-flow-plugin (groovy-like script) to define the work flow (a lot of other jobs involved). It is not easy to get the static relationship of all of jobs used in the definition and build-pipeline-plugin (calculating the dependency for layout [project grid/build grid] based on Upstream/Downstream) can't get the whole picture of what will happen in the kind of build-flow job. We just want to show the detail of the job build status in each build history of build-flow job, which is like buildgraph-view plugin doing. But we want to keep the style of build-pipeline-plugin for layout builds (only build grid, not project grid) but with the mechanism from buildgraph-view plugin to calculate the dependency of job builds.

**Comment by dalvizu** [comment]
> If possible, let us discuss what (requirements) need for this feature: supporting Build Flow job for this plugin. And I can re-implement them.

Yes, certainly, and thanks for explaining your use-case, this sounds like a common pain point. In my own pipeline I use job-dsl to generate the static jobs, for the same reason. It would be nice to support build-flow as well.

My requirement is to not couple the pipeline and build-flow plugin together. The way I see doing this is to have the build-flow be an optional dependency, and expose this option as an implementation of  ProjectGridBuilder. If build-flow is not installed then this just does not show up as a configurable option. If it does, I see it as a new configurable option:

```
  Layout: Based on build-flow plugin layout
```

> we want to keep the style of build-pipeline-plugin for layout builds

Sorry I haven't had time to investigate this more fully, but it sounds like this is an issue in doing that implementation?

**Comment by dalvizu** [comment]
@cdenneen thanks for explaining your use of build-flow, I understand now

**Comment by tangkun75** [comment]
Thanks for your suggestion, @dalvizu 
Now I am trying to create an extension plugin (build-pipeline-plugin-extension-layout) for build-pipeline-plugin for adding the new option ("Layout: Based on build-flow plugin layout") and decoupling the dependencies and separating implementation of new layout into this extension (itself), not impacting the build-pipeline-plugin. I'll give your guys a demonstration soon.
Any new requirements, let me know.

**Comment by tangkun75** [comment]
build-pipeline-extension-layout

**Comment by tangkun75** [comment]
Hi  @recena, @dalvizu and @cdenneen,
    Please try it:  https://github.com/tangkun75/build-pipeline-extension-layout. 
    Any problems, let me know.

Thanks,

-Kun

**Comment by dalvizu** [comment]
Hi @tangkun75 - are you looking to maintain this as another jenkins plugin? I'm a fan of this considering the dependency on graphviz.

**Comment by tangkun75** [comment]
This "build-pipeline-plugin-extension-layout" is an extension of build-pipeline-plugin. I don't know how to publish under jenkinsci repositories. The purpose of graphviz used in this extension is for layout.

**Comment by dalvizu** [comment]
If graphviz is not installed, can the plugin still be run?

**Comment by tangkun75** [comment]
If graphviz not install, it can't be run. Because the current implementation use the "graphviz" as layout engine before showing with build pipeline style. So I add "graphviz" as one dependency:
https://github.com/tangkun75/build-pipeline-plugin-extension-layout/blob/master/README.md

**Comment by dalvizu** [comment]
Okay thanks for explaining that. There are two routes we can go:

Option #1 is to publish your plugin like any other plugin: albeit, it is one that only adds functionality for another plugin. There are instructions on how to do this here:
https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins

Option #2 is to incorporate this into `build-pipeline-plugin`, and have the option show up only if build-flow is installed, which I believe is the default behavior. I am however very worried about user frustration by requiring the installation of graphviz - it would reflect on the quality of the build-pipeline plugin as a whole.

My preference would be option #1.

**Comment by tangkun75** [comment]
Thanks @dalvizu,
    I prefer option 1 too.

**Comment by dalvizu** [comment]
Okay great - closing this out

**Pull request closed without merging**
