### PR TITLE
Fixing and adding tests

### PR DESCRIPTION
**Pull request by KostyaSha**
- updated selenium, guava required for tests run
- added test for re-run button
- debugging xpath issue with wrong buttons pressed

### CODE REVIEW

**Comment by KostyaSha** [comment]
for @patbos

**Comment by KostyaSha** [comment]
```
Results :

Tests run: 83, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by KostyaSha** [comment]
@patbos do you want it test before merge?

**Comment by patbos** [comment]
+1
Great work!

Results :
Tests run: 83, Failures: 0, Errors: 0, Skipped: 0

**Pull request merged**
