### PR TITLE
[JENKINS-31088] show displayName by default

### PR DESCRIPTION
**Pull request by ovorobio**
Rework of original PR: https://github.com/jenkinsci/build-pipeline-plugin/pull/82

### CODE REVIEW

**Comment by ovorobio** [comment]
Unfortunately I don't have an expertise in writing test, any help will be much appreciated

**Comment by dalvizu** [comment]
:+1: cc @recena

**Comment by recena** [comment]
:+1:

**Comment by recena** [comment]
@ovorobio a screenshot would be great in this PR

**Comment by ovorobio** [comment]
### Before
before
### After
after

@recena here screenshots

**Comment by dserodio** [comment]
👍 Great, looking forward to this!

**Pull request merged**
